# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HermanSoftwareSolutions.MediaVault
PackageVersion: 1.0.10
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/HERMAN-Software-Solutions/Media-Vault-Desktop/releases/download/v1.0.10/MediaVault-Setup-1.0.10.exe
  InstallerSha256: A66073177EE5D88789414FBB4CD0DEDA85AD3AFDCDA1D0CCBB413BC0004ACC1F
ManifestType: installer
ManifestVersion: 1.12.0
