# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: HermanSoftwareSolutions.MediaVault
PackageVersion: 1.0.10
PackageLocale: en-US
Publisher: Herman Software Solutions LImited
PackageName: MediaVault Desktop
License: MIT License
Copyright: Copyright © 2026 MediaVault — HERMAN Software Solutions
ShortDescription: free youtube and multi site downloader with inapp preview mini player and no ads
ManifestType: defaultLocale
ManifestVersion: 1.12.0
